#!/usr/bin/env python3
"""Generate wiki/index.md from the frontmatter of every page.

The index is the wiki's catalogue: it is how you (and the assistant) find out what exists
before deciding what a change affects. Hand-maintaining it guarantees it goes stale, so it is
generated from the `title`, `type` and `summary` fields every page already carries.

Usage:
    python3 scripts/build_index.py            # write the index
    python3 scripts/build_index.py --check    # exit 1 if stale (used by `make lint`)
"""

from __future__ import annotations

import sys
from collections import defaultdict
from datetime import date

from wikilib import INDEX, TYPE_LABELS, TYPES, pages

HEADER = """---
title: Index
type: index
summary: Catalogue of every page in this wiki, grouped by type.
---

<!-- GENERATED by scripts/build_index.py — do not edit by hand. Run `make index`. -->

# Index

Every page in the wiki. {count} {noun}, {stubs} of them stubs, last built {built}.

See [Log](log.md) for what changed and when.
"""

EMPTY = """
*The wiki is empty. Drop something into `inbox/` and run `/ingest`.*
"""


def render() -> str:
    by_type: dict[str, list] = defaultdict(list)
    stubs = 0
    for page in pages():
        by_type[page.get("type") or "untyped"].append(page)
        if page.get("status") == "stub":
            stubs += 1

    total = sum(len(v) for v in by_type.values())
    out = [HEADER.format(
        count=total,
        noun="page" if total == 1 else "pages",
        stubs=stubs,
        built=date.today().isoformat(),
    )]

    if not total:
        out.append(EMPTY)
        return "".join(out)

    # Known types first, in schema order; anything unexpected afterwards so it is visible.
    ordered = [t for t in TYPES if t in by_type] + sorted(set(by_type) - set(TYPES))

    for type_name in ordered:
        entries = sorted(by_type[type_name], key=lambda p: (p.get("title") or p.path.stem).lower())
        label = TYPE_LABELS.get(type_name, f"Untyped ({type_name})")
        out.append(f"\n## {label} ({len(entries)})\n\n")
        for page in entries:
            title = page.get("title") or page.path.stem
            summary = page.get("summary") or "*no summary*"
            mark = " `stub`" if page.get("status") == "stub" else ""
            status = page.get("status")
            if status and status != "stub":
                mark = f" `{status}`"
            out.append(f"- [{title}]({page.wiki_rel}){mark} — {summary}\n")

    return "".join(out)


def main() -> int:
    content = render()
    current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""

    # The build date changes daily; ignore it when deciding whether the index is stale.
    def strip_date(text: str) -> str:
        return "\n".join(l for l in text.splitlines() if "last built" not in l)

    if strip_date(current) == strip_date(content):
        print("index: up to date")
        return 0

    if "--check" in sys.argv:
        print("index: STALE — run `make index`", file=sys.stderr)
        return 1

    INDEX.write_text(content, encoding="utf-8")
    print(f"index: written ({len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
