#!/usr/bin/env python3
"""Generate the wiki's derived pages from the frontmatter every page already carries.

Three artefacts, all regenerated wholesale, none ever edited by hand:

    content/_index.md    the catalogue — what exists, grouped by type
    content/tags.md     the same pages grouped by tag, which is the axis that crosses types
    a `Linked from` block at the foot of each page — backlinks, so the site has what
                     Obsidian gives you for free

Hand-maintaining any of these guarantees they go stale, so none of them is hand-maintained.

Usage:
    python3 scripts/build_index.py            # write them
    python3 scripts/build_index.py --check    # exit 1 if stale (used by `make build`)
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from datetime import date

from wikilib import (INDEX, TAGS, TYPE_LABELS, TYPES, Page, inbound_links,
                     pages, replace_block)

INDEX_HEADER = """---
title: Index
type: index
description: Catalogue of every page in this wiki, grouped by type.
---

<!-- GENERATED by scripts/build_index.py — do not edit by hand. Run `make index`. -->

# Index

A personal knowledge wiki that an AI assistant maintains. You decide what goes in and what is true;
the assistant reads new material, works out which pages it affects, writes them, keeps the links and
this catalogue correct, and records what happened in the [Log](log.md). The pages are plain Markdown
files — no database, no lock-in, readable in any editor in ten years' time.

There are two ways in. Tell the assistant something you know, and it writes it down on the page it
belongs to, with the date you said it. Or hand it a document, and it keeps the original, summarises
it on a source page and folds what it says into the pages it affects. Either way, every statement in
the wiki traces back to where it came from, and you can ask questions that are answered from the
pages, with links. A page counts as checked only once you have confirmed it yourself.

The idea is the [LLM Wiki](topics/llm-wiki.md) pattern: knowledge is compiled into linked pages once,
rather than looked up in raw documents on every question. Every page is written in the
[Open Knowledge Format](topics/open-knowledge-format.md), so any other agent can read the wiki
without special tools. [How this wiki works](topics/how-this-wiki-works.md) explains the details.

This wiki is **step 1** of a two-step educational series. Step 2,
[okf-productdocumentation](https://github.com/marcelRonner/okf-productdocumentation), applies the
same ideas to the documentation of a software product. To set up a wiki like this one yourself, see
the [okf-llm-wiki repository](https://github.com/marcelRonner/okf-llm-wiki).

Below is every page in the wiki: {count} {noun}, {stubs} of them {stub_noun}, last built {built}.

See [Tags](tags.md) for the same pages grouped by subject, and [Log](log.md) for what changed
and when.
"""

TAGS_HEADER = """---
title: Tags
type: tags
description: Every tag in use, and the pages carrying it.
---

<!-- GENERATED by scripts/build_index.py — do not edit by hand. Run `make index`. -->

# Tags

Tags cut across the type folders — a page about one project and a page about one decision can
share a subject. {count} {noun} in use, last built {built}.

See [Index](_index.md) for every page grouped by type instead.
"""

EMPTY = """
*The wiki is empty. Drop something into `inbox/` and run `/ingest`, or just run `/note`.*
"""

def marker(page: Page) -> str:
    status = page.get("status")
    return f" `{status}`" if status else ""


def render_index(all_pages: list[Page]) -> str:
    by_type: dict[str, list[Page]] = defaultdict(list)
    stubs = 0
    for page in all_pages:
        by_type[page.get("type") or "untyped"].append(page)
        if page.get("status") == "draft":
            stubs += 1

    total = sum(len(v) for v in by_type.values())
    out = [INDEX_HEADER.format(
        count=total,
        noun="page" if total == 1 else "pages",
        stubs=stubs,
        stub_noun="a stub" if stubs == 1 else "stubs",
        built=date.today().isoformat(),
    )]

    if not total:
        out.append(EMPTY)
        return "".join(out)

    # Known types first, in schema order; anything unexpected afterwards so it is visible.
    ordered = [t for t in TYPES if t in by_type] + sorted(set(by_type) - set(TYPES))

    for type_name in ordered:
        entries = sorted(by_type[type_name], key=lambda p: (p.get("title") or p.path.stem).lower())
        label = TYPE_LABELS.get(type_name, f"Untyped ({type_name})")
        out.append(f"\n## {label} ({len(entries)})\n\n")
        for page in entries:
            title = page.get("title") or page.path.stem
            description = page.get("description") or "*no description*"
            out.append(f"- [{title}]({page.wiki_rel}){marker(page)} — {description}\n")

    return "".join(out)


def render_tags(all_pages: list[Page]) -> str:
    by_tag: dict[str, list[Page]] = defaultdict(list)
    for page in all_pages:
        for tag in page.tags():
            by_tag[tag].append(page)

    out = [TAGS_HEADER.format(
        count=len(by_tag),
        noun="tag" if len(by_tag) == 1 else "tags",
        built=date.today().isoformat(),
    )]

    if not by_tag:
        out.append("\n*No page carries a tag yet.*\n")
        return "".join(out)

    # Most used first: the shape of the wiki's subjects is more useful than the alphabet.
    for tag in sorted(by_tag, key=lambda t: (-len(by_tag[t]), t)):
        entries = sorted(by_tag[tag], key=lambda p: (p.get("title") or p.path.stem).lower())
        out.append(f"\n## {tag} ({len(entries)})\n\n")
        for page in entries:
            title = page.get("title") or page.path.stem
            label = TYPE_LABELS.get(page.get("type"), page.get("type") or "untyped")
            out.append(f"- [{title}]({page.wiki_rel}){marker(page)} — {label.rstrip('s')}\n")

    return "".join(out)


BACKLINKS_OPEN = "<!-- backlinks:start GENERATED by `make index` — do not edit -->"
BACKLINKS_CLOSE = "<!-- backlinks:end -->"


def backlinks_body(page: Page, incoming: list[Page]) -> str:
    """What goes between the backlink markers. Empty when nothing links here."""
    if not incoming:
        return ""
    lines = ["", "## Linked from", ""]
    for other in sorted(set(incoming), key=lambda p: (p.get("title") or p.path.stem).lower()):
        title = other.get("title") or other.path.stem
        lines.append(f"- [{title}]({relative(page.path, other.path)})")
    return "\n".join(lines)


def relative(source, target) -> str:
    """A relative Markdown link between two pages — the form both Obsidian and Hugo read."""
    import os
    return os.path.relpath(target, source.parent).replace(os.sep, "/")


GENERATED_RE = re.compile(r"^generated:\n(?:  \w+: .*\n)+", re.M)


def apply_generated(all_pages: list[Page], check: bool) -> list[str]:
    """Stamp OKF v0.2's `generated: { by, at }` from `updated:`.

    v0.2 replaced v0.1's flat `timestamp` with this. It duplicates `updated:`, which is why it is
    stamped rather than hand-written — two dates maintained by hand drift, and the wiki has no way
    to notice. `by: wiki-keeper/1.0` follows the specification's versioned tool-actor convention;
    the date-only local field is expressed as midnight UTC. A page the owner has confirmed says so separately, under
    `verified:`.
    """
    changed = []
    for page in all_pages:
        updated = page.get("updated")
        if not updated:
            continue
        block = f"generated:\n  by: wiki-keeper/1.0\n  at: {updated}T00:00:00Z\n"
        if GENERATED_RE.search(page.text):
            new = GENERATED_RE.sub(block, page.text, count=1)
        else:
            new = page.text.replace(f"updated: {updated}\n", f"updated: {updated}\n{block}", 1)
        if new != page.text:
            changed.append(page.wiki_rel)
            if not check:
                page.path.write_text(new, encoding="utf-8")
    return changed


def apply_backlinks(all_pages: list[Page], check: bool) -> list[str]:
    """Stamp each page's backlinks block. Returns the pages that were (or would be) changed."""
    incoming = inbound_links(all_pages)
    changed = []

    for page in all_pages:
        body = backlinks_body(page, incoming[page.path.resolve()])
        if BACKLINKS_OPEN in page.text:
            updated = replace_block(page.text, "backlinks", body)
        else:
            updated = f"{page.text.rstrip(chr(10))}\n\n{BACKLINKS_OPEN}\n{body}\n{BACKLINKS_CLOSE}\n"

        if updated != page.text:
            changed.append(page.wiki_rel)
            if not check:
                page.path.write_text(updated, encoding="utf-8")

    return changed


def write(path, content: str, check: bool, label: str, stale: list[str]) -> None:
    current = path.read_text(encoding="utf-8") if path.exists() else ""

    # The build date changes daily; ignore it when deciding whether the page is stale.
    def strip_date(text: str) -> str:
        return "\n".join(l for l in text.splitlines() if "last built" not in l)

    if strip_date(current) == strip_date(content):
        return
    if check:
        stale.append(label)
    else:
        path.write_text(content, encoding="utf-8")
        print(f"index: wrote {label}")


def main() -> int:
    check = "--check" in sys.argv
    stale: list[str] = []

    all_pages = pages()

    # Backlinks first: they change page files, and the index is built from those same files.
    stamped = apply_generated(all_pages, check)
    if stamped:
        if check:
            stale.append(f"generated: on {len(stamped)} page(s)")
        else:
            print(f"index: generated: stamped on {len(stamped)} page(s)")
            all_pages = pages()

    touched = apply_backlinks(all_pages, check)
    if touched:
        if check:
            stale.append(f"backlinks on {len(touched)} page(s)")
        else:
            print(f"index: backlinks updated on {len(touched)} page(s)")
        all_pages = pages()

    write(INDEX, render_index(all_pages), check, "content/_index.md", stale)
    write(TAGS, render_tags(all_pages), check, "content/tags.md", stale)

    if stale:
        print(f"index: STALE — run `make index` ({'; '.join(stale)})", file=sys.stderr)
        return 1

    print("index: up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
