#!/usr/bin/env python3
"""Generate the wiki's derived pages from the frontmatter every page already carries.

Three artefacts, all regenerated wholesale, none ever edited by hand:

    content/_index.md    the catalogue — what exists, grouped by type
    content/tags.md     the same pages grouped by tag, which is the axis that crosses types
    a `Linked from` block at the foot of each page — backlinks, so the site has what
                     Obsidian gives you for free

Hand-maintaining any of these guarantees they go stale, so none of them is hand-maintained.

Usage:
    python3 scripts/build_index.py            # write them
    python3 scripts/build_index.py --check    # exit 1 if stale (used by `make build`)
"""

from __future__ import annotations

import sys
from collections import defaultdict
from datetime import date

from wikilib import (INDEX, TAGS, TYPE_LABELS, TYPES, Page, inbound_links,
                     pages, replace_block)

# `type: docs` is Hugo's, not this wiki's. Docsy spans the sidebar across every folder only when
# the home page's type is `docs` (see the theme's _partials/sidebar-args.html); with anything else
# the nav collapses to whichever folder you happen to be in, and there is no way to get from
# topics/ to projects/. This page is the catalogue, so the whole tree is exactly what it should
# show. Nothing reads a `type` here — the page is excluded from the lint and the index by name.
INDEX_HEADER = """---
title: Index
type: docs
summary: Catalogue of every page in this wiki, grouped by type.
---

<!-- GENERATED by scripts/build_index.py — do not edit by hand. Run `make index`. -->

# Index

Every page in the wiki. {count} {noun}, {stubs} of them {stub_noun}, last built {built}.

See [Tags](tags.md) for the same pages grouped by subject, and [Log](log.md) for what changed
and when.
"""

TAGS_HEADER = """---
title: Tags
type: tags
summary: Every tag in use, and the pages carrying it.
---

<!-- GENERATED by scripts/build_index.py — do not edit by hand. Run `make index`. -->

# Tags

Tags cut across the type folders — a page about one project and a page about one decision can
share a subject. {count} {noun} in use, last built {built}.

See [Index](_index.md) for every page grouped by type instead.
"""

EMPTY = """
*The wiki is empty. Drop something into `inbox/` and run `/ingest`, or just run `/note`.*
"""

def marker(page: Page) -> str:
    status = page.get("status")
    return f" `{status}`" if status else ""


def render_index(all_pages: list[Page]) -> str:
    by_type: dict[str, list[Page]] = defaultdict(list)
    stubs = 0
    for page in all_pages:
        by_type[page.get("type") or "untyped"].append(page)
        if page.get("status") == "stub":
            stubs += 1

    total = sum(len(v) for v in by_type.values())
    out = [INDEX_HEADER.format(
        count=total,
        noun="page" if total == 1 else "pages",
        stubs=stubs,
        stub_noun="a stub" if stubs == 1 else "stubs",
        built=date.today().isoformat(),
    )]

    if not total:
        out.append(EMPTY)
        return "".join(out)

    # Known types first, in schema order; anything unexpected afterwards so it is visible.
    ordered = [t for t in TYPES if t in by_type] + sorted(set(by_type) - set(TYPES))

    for type_name in ordered:
        entries = sorted(by_type[type_name], key=lambda p: (p.get("title") or p.path.stem).lower())
        label = TYPE_LABELS.get(type_name, f"Untyped ({type_name})")
        out.append(f"\n## {label} ({len(entries)})\n\n")
        for page in entries:
            title = page.get("title") or page.path.stem
            summary = page.get("summary") or "*no summary*"
            out.append(f"- [{title}]({page.wiki_rel}){marker(page)} — {summary}\n")

    return "".join(out)


def render_tags(all_pages: list[Page]) -> str:
    by_tag: dict[str, list[Page]] = defaultdict(list)
    for page in all_pages:
        for tag in page.tags():
            by_tag[tag].append(page)

    out = [TAGS_HEADER.format(
        count=len(by_tag),
        noun="tag" if len(by_tag) == 1 else "tags",
        built=date.today().isoformat(),
    )]

    if not by_tag:
        out.append("\n*No page carries a tag yet.*\n")
        return "".join(out)

    # Most used first: the shape of the wiki's subjects is more useful than the alphabet.
    for tag in sorted(by_tag, key=lambda t: (-len(by_tag[t]), t)):
        entries = sorted(by_tag[tag], key=lambda p: (p.get("title") or p.path.stem).lower())
        out.append(f"\n## {tag} ({len(entries)})\n\n")
        for page in entries:
            title = page.get("title") or page.path.stem
            label = TYPE_LABELS.get(page.get("type"), page.get("type") or "untyped")
            out.append(f"- [{title}]({page.wiki_rel}){marker(page)} — {label.rstrip('s')}\n")

    return "".join(out)


BACKLINKS_OPEN = "<!-- backlinks:start GENERATED by `make index` — do not edit -->"
BACKLINKS_CLOSE = "<!-- backlinks:end -->"


def backlinks_body(page: Page, incoming: list[Page]) -> str:
    """What goes between the backlink markers. Empty when nothing links here."""
    if not incoming:
        return ""
    lines = ["", "## Linked from", ""]
    for other in sorted(set(incoming), key=lambda p: (p.get("title") or p.path.stem).lower()):
        title = other.get("title") or other.path.stem
        lines.append(f"- [{title}]({relative(page.path, other.path)})")
    return "\n".join(lines)


def relative(source, target) -> str:
    """A relative Markdown link between two pages — the form both Obsidian and Hugo read."""
    import os
    return os.path.relpath(target, source.parent).replace(os.sep, "/")


def apply_backlinks(all_pages: list[Page], check: bool) -> list[str]:
    """Stamp each page's backlinks block. Returns the pages that were (or would be) changed."""
    incoming = inbound_links(all_pages)
    changed = []

    for page in all_pages:
        body = backlinks_body(page, incoming[page.path.resolve()])
        if BACKLINKS_OPEN in page.text:
            updated = replace_block(page.text, "backlinks", body)
        else:
            updated = f"{page.text.rstrip(chr(10))}\n\n{BACKLINKS_OPEN}\n{body}\n{BACKLINKS_CLOSE}\n"

        if updated != page.text:
            changed.append(page.wiki_rel)
            if not check:
                page.path.write_text(updated, encoding="utf-8")

    return changed


def write(path, content: str, check: bool, label: str, stale: list[str]) -> None:
    current = path.read_text(encoding="utf-8") if path.exists() else ""

    # The build date changes daily; ignore it when deciding whether the page is stale.
    def strip_date(text: str) -> str:
        return "\n".join(l for l in text.splitlines() if "last built" not in l)

    if strip_date(current) == strip_date(content):
        return
    if check:
        stale.append(label)
    else:
        path.write_text(content, encoding="utf-8")
        print(f"index: wrote {label}")


def main() -> int:
    check = "--check" in sys.argv
    stale: list[str] = []

    all_pages = pages()

    # Backlinks first: they change page files, and the index is built from those same files.
    touched = apply_backlinks(all_pages, check)
    if touched:
        if check:
            stale.append(f"backlinks on {len(touched)} page(s)")
        else:
            print(f"index: backlinks updated on {len(touched)} page(s)")
        all_pages = pages()

    write(INDEX, render_index(all_pages), check, "content/_index.md", stale)
    write(TAGS, render_tags(all_pages), check, "content/tags.md", stale)

    if stale:
        print(f"index: STALE — run `make index` ({'; '.join(stale)})", file=sys.stderr)
        return 1

    print("index: up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
