#!/usr/bin/env python3
"""Regenerate everything that restates the page types, from schema.yml.

The type list used to exist in six places read by three different audiences — the scripts, the
assistant, and you — with nothing checking they agreed. That is a worse bug than it sounds: when
`.github/` and the linter disagree about which types exist, the assistant trusts both, and
resolves the contradiction by rewriting your *pages* to satisfy the linter.

So the schema is declared once in schema.yml and stamped into the files that need to restate it:

    AGENTS.md                         the page-type table + the frontmatter example
    README.md                         the content/ layout tree
    content/<folder>/_index.md        the section pages Hugo builds the sidebar from

This script also writes two things into the layout GitHub Copilot reads:

    .claude/rules/*.md   -> .github/instructions/*.instructions.md  (`paths:` -> `applyTo:`)
    .claude/skills/*/    -> .github/prompts/*.prompt.md             (a typed door, not a copy)

Edit the left-hand side. `make build` fails if the right-hand side has drifted.

Neither is a copy of the instructions themselves. VS Code reads `AGENTS.md` at the workspace root
and discovers skills from `.claude/skills/` directly, so the contract and the four operations are
read where they are written. What the two phases exist for:

  * Scoped rules, because the `.claude/rules` location Copilot supports is user-profile only
    (`~/.claude/rules`); a project's scoped rules have to be restated under `.github/`.
  * Typing `/note`. Copilot matches a skill on its description rather than on a name you type, and
    "nothing enters or leaves the wiki except through these four" means four doors the owner can
    type. The prompt files are those doors and nothing else: each names its skill and stops, so the
    protocol still exists in exactly one place.

If Copilot ever reads project-level `.claude/rules/` and lets a skill be invoked by name, both
phases and the whole `.github/` directory can go.

Usage:
    python3 scripts/build_schema.py            # write the generated blocks
    python3 scripts/build_schema.py --check    # exit 1 if any are stale (used by `make build`)
"""

from __future__ import annotations

import sys

from wikilib import ROOT, TYPE_INFO, WIKI, replace_block

INSTRUCTIONS = ROOT / "AGENTS.md"
README = ROOT / "README.md"

RULES_DIR = ROOT / ".claude" / "rules"
SKILLS_DIR = ROOT / ".claude" / "skills"
COPILOT = ROOT / ".github"

GENERATED_NOTE = (
    "<!-- GENERATED by scripts/build_schema.py from schema.yml — do not edit. "
    "Run `make schema`. -->"
)


MIRROR_NOTE = (
    "<!-- GENERATED by scripts/build_schema.py — do not edit. Edit {source} and run "
    "`make schema`. -->"
)


def split_frontmatter(text: str) -> tuple[str, str]:
    """Return (frontmatter-without-fences, body). Frontmatter is '' when there is none."""
    if not text.startswith("---\n"):
        return "", text
    end = text.index("\n---\n", 3)
    return text[4:end], text[end + 5:]


def copilot_mirror() -> dict:
    """The .github/ tree, rendered from the Claude-native sources. Keyed by path."""
    out = {}

    # Path-scoped rules. Copilot takes one comma-separated string where the source YAML has a list.
    for src in sorted(RULES_DIR.glob("*.md")):
        fm, body = split_frontmatter(src.read_text(encoding="utf-8"))
        globs = [ln.strip().lstrip("-").strip() for ln in fm.splitlines() if ln.strip().startswith("-")]
        if not globs:
            raise SystemExit(f"schema: {src.relative_to(ROOT)} has no `paths:` entries")
        rel = f".claude/rules/{src.name}"
        out[COPILOT / "instructions" / f"{src.stem}.instructions.md"] = (
            f'---\napplyTo: "{",".join(globs)}"\n---\n\n'
            + MIRROR_NOTE.format(source=rel) + "\n" + body
        )

    # Typed doors for Copilot, which matches skills on description rather than on a name you type.
    # Deliberately not a copy of the skill: it names it and stops, so there is one protocol, not two.
    for src in sorted(SKILLS_DIR.glob("*/SKILL.md")):
        name = src.parent.name
        fm, _ = split_frontmatter(src.read_text(encoding="utf-8"))
        desc = next(ln.split(":", 1)[1].strip() for ln in fm.splitlines() if ln.startswith("description:"))
        rel = f".claude/skills/{name}/SKILL.md"
        out[COPILOT / "prompts" / f"{name}.prompt.md"] = (
            f"---\nagent: agent\ndescription: {desc}\n---\n\n"
            + MIRROR_NOTE.format(source=rel) + "\n\n"
            f"Run the **{name}** operation.\n\n"
            f"Read `{rel}` and follow it exactly, including every checklist item in it and in\n"
            "`AGENTS.md`. Do not improvise an alternative — this file is only the door, the skill is\n"
            "the procedure. Anything the owner typed after the command is the input to it.\n"
        )

    return out


def types_table() -> str:
    rows = ["| Type | Folder | Holds |", "|---|---|---|"]
    for name, spec in TYPE_INFO.items():
        rows.append(f"| `{name}` | `content/{spec['folder']}/` | {spec['holds']} |")
    return "\n".join(rows)


def frontmatter_example() -> str:
    enum = " | ".join(TYPE_INFO)
    return "\n".join([
        "```yaml",
        "---",
        "title: Human readable name",
        f"type: {enum}",
        "summary: One sentence. This is what appears in the index — make it worth reading.",
        "created: YYYY-MM-DD",
        "updated: YYYY-MM-DD",
        "tags: [lowercase-kebab, another]",
        "sources: [sources/some-source.md]   # source pages this page draws on; omit if none",
        "---",
        "```",
    ])


def section_pages() -> dict:
    """One Hugo section page per type folder, keyed by path.

    Hugo builds the sidebar from these: a folder with no `_index.md` gets a bare, untitled
    listing. They restate schema.yml, so they are stamped from it rather than hand-written —
    `weight` follows the declaration order in schema.yml, which is the order the index uses.
    """
    out = {}
    for i, spec in enumerate(TYPE_INFO.values(), start=1):
        path = WIKI / spec["folder"] / "_index.md"
        out[path] = "\n".join([
            "---",
            f"title: {spec['label']}",
            f"description: {spec['holds']}",
            f"weight: {i * 10}",
            "---",
            "",
            GENERATED_NOTE,
            "",
        ])
    return out


def layout_tree() -> str:
    entries = [
        ("_index.md", "GENERATED catalogue — do not edit, run `make index`"),
        ("tags.md", "GENERATED tag listing — every tag, and what carries it"),
        ("log.md", "append-only history of every operation"),
    ]
    entries += [(f"{spec['folder']}/", spec["short"]) for spec in TYPE_INFO.values()]

    width = max(len(name) for name, _ in entries) + 2
    lines = ["```"]
    lines.append("inbox/              drop new material here — should be empty when you are done")
    lines.append("raw/                originals, immutable, never edited")
    lines.append("content/            the vault, and Hugo's content directory")
    for i, (name, desc) in enumerate(entries):
        branch = "└──" if i == len(entries) - 1 else "├──"
        lines.append(f"{branch} {name.ljust(width)}{desc}")
    lines.append("templates/          the shape of each page type")
    lines.append("scripts/            index generation and the mechanical checks")
    lines.append("schema.yml          the page types — edit here, run `make schema`")
    lines.append("AGENTS.md           the schema in prose: layers, operations, provenance, rules")
    lines.append("CLAUDE.md           one line, importing AGENTS.md for Claude Code")
    lines.append(".claude/            rules/ per-folder writing rules, skills/ the four operations")
    lines.append(".github/            GENERATED — scoped rules in Copilot's dialect, and typed doors")
    lines.append("hugo.yaml           the site build: Docsy as a Hugo module, and the theme's settings")
    lines.append("layouts/            the one template this site overrides — see _markup/render-link.html")
    lines.append("go.mod  package.json  pinned versions of the theme and its assets")
    lines.append("```")
    return "\n".join(lines)


BLOCKS = {
    INSTRUCTIONS: {"schema-types": types_table, "schema-frontmatter": frontmatter_example},
    README: {"schema-layout": layout_tree},
}


def main() -> int:
    check = "--check" in sys.argv
    stale: list[str] = []

    for path, blocks in BLOCKS.items():
        if not path.exists():
            print(f"schema: {path.relative_to(ROOT)} is missing", file=sys.stderr)
            return 1
        current = path.read_text(encoding="utf-8")
        updated = current
        for name, render in blocks.items():
            updated = replace_block(updated, name, render())
        if updated == current:
            continue
        if check:
            stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(updated, encoding="utf-8")
            print(f"schema: updated {path.relative_to(ROOT)}")

    wanted_files = dict(section_pages())
    wanted_files.update(copilot_mirror())

    # Anything left in the mirrored directories has no source any more — a rule or operation that
    # was renamed or deleted. Left alone it would go on being loaded by Copilot for ever.
    for existing in sorted((COPILOT / "instructions").glob("*.md")) + sorted((COPILOT / "prompts").glob("*.md")):
        if existing in wanted_files:
            continue
        if check:
            stale.append(f"{existing.relative_to(ROOT)} (orphaned)")
        else:
            existing.unlink()
            print(f"schema: removed {existing.relative_to(ROOT)} — no source in .claude/")

    for path, wanted in wanted_files.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == wanted:
            continue
        if check:
            stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(wanted, encoding="utf-8")
            print(f"schema: updated {path.relative_to(ROOT)}")

    if stale:
        print(f"schema: STALE — run `make schema` ({', '.join(stale)})", file=sys.stderr)
        return 1

    print("schema: up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
